spring:
  rsocket:
    server:
      port: 7000
      transport: websocket
  data:
    mongodb:
      host: localhost
      port: 33843
      database: rsocket

logging:
  level:
    root: INFO
    com.slalom.rsocket.demo: DEBUG
    org.springframework.beans: INFO
    org.mongodb.driver.protocol.command: INFO
