spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
logging:
  level:
    root: INFO
    sun.rmi.loader: INFO
    sun.rmi.transport.tcp: INFO
    javax.management.remote.rmi: INFO
    com.slalom.rsocket.demo: DEBUG
    org.springframework.beans: DEBUG
    org.springframework.data.redis: DEBUG
    redis.embedded;: DEBUG
