spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
logging:
  level:
    root: INFO
    com.slalom.rsocket.demo: DEBUG
    org.springframework.beans: INFO
    org.springframework.data.redis: DEBUG
    redis.embedded;: DEBUG
